### ISSUE TITLE
spike times should be in seconds

### ISSUE THREAD

**Issue by bendichter** [rutishauserlab/recogmem-release-NWB#5]
For the dataset that is published on DANDI [here](https://dandiarchive.org/dandiset/000004/draft), it looks like the spike time are in milliseconds, but they are supposed to be in seconds. This is going to cause problems with any NWB tools that try to run any analysis or visualization on these files.

**Comment by nandchandravadia** [comment]
Hi Ben, thanks for pointing this out! I will change the spike times into seconds.

**Comment by nandchandravadia** [comment]
This has been resolved. See: https://gui.dandiarchive.org/#/dandiset/5e6ff4140fe0ec33e6b3d5d2
